### PR TITLE
Target API 28, gradle plugin 3.2.0

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by PierfrancescoSoffritti** [comment]
looks good, thanks!!

**Comment by PierfrancescoSoffritti** [comment]
hey, @talklittle, I didn't check that the PR was on master. Is it ok if I revert it? could you re-make it on the dev branch instead?

**Comment by talklittle** [comment]
Sure, sorry about that

**Comment by PierfrancescoSoffritti** [comment]
Great, thanks!

**Pull request merged**
