### PR TITLE
fix some leak and got stop methed

### PR DESCRIPTION
**Pull request by billdizl**
can by YouTubePlayerView get youTubePlayer  ,may be  youTubePlayer is null, because  youTubePlayer may not initFinished

### CODE REVIEW

**Comment by billdizl** [comment]
https://github.com/billdizl/android-youtube-player

**Comment by PierfrancescoSoffritti** [comment]
Hi, the purpose of this PR is not clear. Could you explain?
Also please only send PRs to the dev branch :)

**Comment by billdizl** [comment]
> Hi, the purpose of this PR is not clear. Could you explain? Also please only send PRs to the dev branch :)

my english real poor, may i speak chinese?
1.在sdk中,判断网络状态时context未使用application造成的内存泄漏的问题
2.工具类中有io流未close,造成的内存泄漏
3.引入youtube的stop方法,来暂停视频视频( https://developers.google.com/youtube/iframe_api_reference#Playback_controls )
player.stopVideo():Void
Stops and cancels loading of the current video. This function should be reserved for rare situations when you know that the user will not be watching additional video in the player. If your intent is to pause the video, you should just call the [pauseVideo](https://developers.google.com/youtube/iframe_api_reference#pauseVideo) function. If you want to change the video that the player is playing, you can call one of the queueing functions without calling stopVideo first.

Important: Unlike the [pauseVideo](https://developers.google.com/youtube/iframe_api_reference#pauseVideo) function, which leaves the player in the paused (2) state, the stopVideo function could put the player into any not-playing state, including ended (0), paused (2), video cued (5) or unstarted (-1).
4.在oppo a15 和a15s手机中,因多次webview.destory引发的程序崩溃的问题修复

**Comment by billdizl** [comment]
此次修改,我们app已经上线并运行良好,With this modification, our app has been online and running well

**Comment by PierfrancescoSoffritti** [comment]
Hi, why don't you write in Chinese in Google Translate and copy the English version here?

Also cleaning up the Pull Request would help explaining what you intend to do, right now there are a lot of unrelated changes.

**Comment by PierfrancescoSoffritti** [comment]
Closing this PR, as it's not clear what the owner's intent is.

**Pull request closed without merging**
