### PR TITLE
Fixes #543

### LINKED ISSUE #543: App crashes with unhelpful error if `autoplay=true` but no `videoId` is provided
This is not a valid configuration, since `autoPlay` is true, but no `videoId` is provided.

```
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:autoPlay="true" />
```
The app crashes with an unhelpful error.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shuffly/com.shuffly.ui.MainActivity}: android.view.InflateException: Binary XML file line #18 in com.shuffly:layout/activity_main: Binary XML file line #18 in com.shuffly:layout/activity_main: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
```

### PR DESCRIPTION
**Pull request by furkanaskin**
I changed throw Exception with Log.e() and also made PlayerUiController hidden.

### CODE REVIEW

**Comment by PierfrancescoSoffritti** [comment]
* Why hiding the UI?
* The configuration is still not valid, I'm not sure that logging the error is enough.

Can you send this PR on the dev branch?

**Comment by furkanaskin** [comment]
Hi @PierfrancescoSoffritti,

I hide the ui because it shows buffer progressbar, seekbar, fullscreen button etc. i think we must hide the ui.
The logging the exception just blocks the crashing app, all progress are same. Maybe we can add toast,snack or other useful ui messages.

**Comment by malliaridis** [comment]
I see the reason why to hide the UI and not allow the app to crash. Is it however an expected behavior for invalid configuration of an XML layout? 

I think the best solution would be that 
* when no video id is provided, the view shows a "missing video icon" (whatever that might be), 
* when a video id is fetched (over the internet for example), a loading video indicator (like default UI) is shown, and 
* when a video id is present just the typical behavior.

The app should in these cases never crash, whether `autoPlay` is `true` or not, because there is a state for "missing video id", **which makes the relation between `videoId` and `autoPlay` complementary and not interdependent** .

In that case, the PR is on the right way and apply a feasible change.

@furkanaskin is the class configured in that way, that shows up again the UI when a video ID is provided in a later state from e.g. the user? Because just hiding the UI might prevent later use of the UI (without showing them up again).

**Comment by furkanaskin** [comment]
@malliaridis, you are right. My solution isn't solve all cases like providing video id in a later state, hiding whole ui isn't a good idea. Your solution looks fine, i'll implement your solution to my pr and then i'll notify you.

**Comment by furkanaskin** [comment]
Oct-03-2020 21-48-32

Hi @malliaridis , @PierfrancescoSoffritti ,

I thought placing a text with an icon in left corner of screen will be nice for users. Icon took from Material Design icons and if you agree with me i'll send my changes. This icon and text will be visible only when videoId is missing.

I want your ideas about text and icon.

**Comment by PierfrancescoSoffritti** [comment]
> when no video id is provided, the view shows a "missing video icon" (whatever that might be),

I would avoid doing this. We are building a library on top of the YouTube player, so the default behaviour should be whatever the YouTube player does. If they show nothing we should probably show nothing as well.

**Comment by malliaridis** [comment]
You are right. After all, adding custom elements will just irritate the users. The default behavior of the website is to redirect to the user to the start page. I don't know what the default behavior of an iframe is in that case.

In our case we could 
* Leave a black view, to prevent layout modifications that only messes up with users' layouts, or
* hide the whole player, which however might change the users' layout and mess it up.

Throwing an exception is of course an option too. See however [my reason not to do so](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/543#issuecomment-703247427).

**Comment by furkanaskin** [comment]
I moved the if statement to **onAttachedToWindow** and now result looks like this : 

`
2020-10-05 08:31:58.593 26926-26926/com.pierfrancescosoffritti.aytplayersample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pierfrancescosoffritti.aytplayersample, PID: 26926
    java.lang.IllegalArgumentException: videoId is not set but autoPlay is set to true. This combination is not possible.
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.onAttachedToWindow(YouTubePlayerView.kt:103)
        at android.view.View.dispatchAttachedToWindow(View.java:19553)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2028)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-10-05 08:31:58.675 2012-2114/system_process E/InputDispatcher: channel '63f94cf com.pierfrancescosoffritti.aytplayersample/com.psoffritti.librarysampleapptemplate.core.SampleAppTemplateActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-10-05 08:31:58.676 2012-2114/system_process E/InputDispatcher: channel '26ea403 com.pierfrancescosoffritti.aytplayersample/com.pierfrancescosoffritti.androidyoutubeplayer.core.sampleapp.examples.simpleExample.SimpleExampleActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-10-05 08:31:58.908 2167-2670/com.google.android.gms.persistent E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202414022@20.24.14 (040700-319035315):2)
        at aewd.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):4)
        at aewg.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):9)
        at aeso.a(Unknown Source:0)
        at rpm.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
        at rlv.c(:com.google.android.gms@202414022@20.24.14 (040700-319035315):1)
        at rlt.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):1)
        at rok.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):6)
        at rok.c(:com.google.android.gms@202414022@20.24.14 (040700-319035315):6)
        at rok.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):63)
        at roo.handleMessage(:com.google.android.gms@202414022@20.24.14 (040700-319035315):71)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at aekz.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):2)
        at aekz.dispatchMessage(:com.google.android.gms@202414022@20.24.14 (040700-319035315):14)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)`

**Pull request closed without merging**
