### PR TITLE
Add more playback rates

### PR DESCRIPTION
**Pull request by santiwanti**
The Youtube Web Client supports any value between 0.25 and 2.0 so I'm guessing this API should be able to do so as well. I have added two commits, one that adds just the missing 0.75, 1.25, and 1.75 increments and one that adds a function to allow any float value. We might have to check what happens if 2.5 or 100 is sent and maybe a doc indicating that only values between 0.25 and 2.0 are valid.

This PR addresses:
https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/1001
https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/992

### CODE REVIEW

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for the PR!

Did you try passing a value bigger than 2? what happens?

**Comment by santiwanti** [comment]
I just tested it which lead me to fix a few bugs I had introduced. 

When calling it with a value greater than 2 the playback rate is set to 2. Should we add a `require` making sure the user never sends a value greater than 2 or less than 0.25? Or should we document the behaviour indicating that any value outside the range 0.25 and 2 will be coerced so 0.1 or negative numbers will be 0.25 and 3 will be 2?

**Comment by santiwanti** [comment]
The difference with `fun setPlaybackRate(playbackRate: Float)` is that for values like 0.45 it will return 0.45 instead of `PlayerConstants.PlaybackRate.UNKNOWN` which is what `  fun setPlaybackRate(playbackRate: PlayerConstants.PlaybackRate)
` returns

**Comment by santiwanti** [comment]
@PierfrancescoSoffritti sorry to bother you. Anything else that should be done on this PR?

**Comment by PierfrancescoSoffritti** [comment]
I have removed the option to use a generic float to set the playback rate, as it doesn't seem necessary and introduces too much ambiguity in the API.

But happy to add the new enums, thanks for your contribution :)

**Comment by santiwanti** [comment]
@PierfrancescoSoffritti the point of being able to set the playback rate with an arbitrary float is that you can set the value to 1.2 or any other value between 0.25 and 2.0 which doens't have an enum value. This is also allowed in the youtube website if you click on playbackrate and select custom.

**Comment by PierfrancescoSoffritti** [comment]
I understand, why is using the predefined values not enough for your use case?

**Comment by santiwanti** [comment]
In my use case we have to allow any value between 0.25 and 2.0 with increments of 0.01. This is for an app for musicians which might want to play the video at arbitrary speeds. I understand if you don't want to implement this. For now I have copied my fork into the project and use that.

**Comment by PierfrancescoSoffritti** [comment]
I see. I think wanting to add a function to set an arbitrary playback speed is a reasonable request.

I will add the method, but it will take some time as I need to make sure the API we are introducing is clear and won't lead to confusing behavior. (And I have limited time to spend on the library)

I have opened #1081 to keep track of this, I will get to it before the end of the year.

**Pull request merged**
