### PR TITLE
feat: Introduce support for Live-VOD mode for live streams

### PR DESCRIPTION
**Pull request by rajeefmk**
The changes included are :

- Introduced Live-VOD (Video on Demand) mode similar which is enabled when user moves the seekbar during live stream.
- Live stream indicator tag is made clickable and now has the same functionality as that of native app wherein it'll restore the live state.
- Seekbar is always visible now and during Live stream, it's progress position value will be that of the video duration.

### CODE REVIEW

**Comment by PierfrancescoSoffritti** [comment]
Great, thanks! expect it available in v8 soon :)

**Comment by PierfrancescoSoffritti** [comment]
If you'd like to take on other issues just let me know!

**Comment by rajeefmk** [comment]
@PierfrancescoSoffritti Absolutely.

**Comment by PierfrancescoSoffritti** [comment]
[issue 132]( https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/issues/132)
this one is similar to the one you just sent

[issue 71](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/issues/71)
this one is also about implementing features from the YouTube app, but probably a bit more challenging

**Comment by rajeefmk** [comment]
@PierfrancescoSoffritti What a coincidence ! I was actually going through this https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/issues/132 very same ticket. 

Continuing the discussion there.

**Comment by PierfrancescoSoffritti** [comment]
I've been testing the new live controls, it's really hard to ensure consistency. The available buffer for some live videos appears to be of 2 hours, for other is different. Therefore is basically impossible to map correctly the video's duration on the seekbar.
Almost all the time, when manually seeking to the start or end of the seekbar the behavior is inconsistent.

I have been trying to find a solution to these problems but I haven't been able to. Do you have any ideas? If it's not possible to solve these issues I'm afraid I will have to revert the changes :/

**Comment by rajeefmk** [comment]
@PierfrancescoSoffritti You're absolutely right. So the seekbar behaviour is directly dependent on how on the total duration of the live session and not precisely when the actual broadcast started. This will definitely create inconsistency. 

I think you'll have to go ahead revert the changes :/ Sorry about that !

**Comment by PierfrancescoSoffritti** [comment]
No worries, it is quite tricky actually. The buffer is behaving like a sliding window, not sure yet how we could implement it.

**Pull request merged**
