### PR TITLE
Videos click will no longer redirect to youtube app.

### PR DESCRIPTION
**Pull request by mrkamiali**

### CODE REVIEW

**Comment by mrkamiali** [comment]
@PierfrancescoSoffritti  here you go I have revert changes and updates the pull request with reference to #464

**Comment by PierfrancescoSoffritti** [comment]
I think you're making a bit of confusion. Now I have two pull requests, the other one still has both changes.

**Comment by mrkamiali** [comment]
> I think you're making a bit of confusion. Now I have two pull requests, the other one still has both changes.

No the call back is not in the other pull request, you are taking time and I keep working on updates as I  needed in my project.

**Comment by mrkamiali** [comment]
And I think that why it makes confusion.

**Comment by PierfrancescoSoffritti** [comment]
Pull requests should be on specific branches, on which you don't write new code. That's why I haven't reviewed it this weekend, there was a bunch of other stuff.

**Comment by mrkamiali** [comment]
> Pull requests should be on specific branches, on which you don't write new code. That's why I haven't reviewed it this weekend, there was a bunch of other stuff.

Ok Buddy... Take your time.

**Comment by PierfrancescoSoffritti** [comment]
This pull request is implementing two different new features. A pull request should be about a single new feature only.
Unfortunately I can't merge this.

**Comment by mrkamiali** [comment]
As you wish , as of my thought I think everything is well settled and well defined. Np

**Pull request closed without merging**
