### PR TITLE
Add fast forward/rewind functionality

### PR DESCRIPTION
**Pull request by AbelTesfaye**
Adds a customizable fast forward/rewind view that can be used for seeking the player

Bug: #132

### CODE REVIEW

**Comment by AbelTesfaye** [comment]
Hi,

This closes #132. But I've not included tests, because I found they would be unreliable and I need more time to figure out how to best make them for these changes. In the meantime, [here is what I have so far](https://github.com/AbelTesfaye/android-youtube-player/tree/feat-forward-rewind-test) ( proceed with caution, its not the cleanest code out there xD )

**Comment by PierfrancescoSoffritti** [comment]
Hey, the animation looks amazing, well done :) I will try to go through the code tomorrow.

**Comment by Tahsin100** [comment]
Hello @PierfrancescoSoffritti. Any update of this feature being merged?

**Comment by PierfrancescoSoffritti** [comment]
Custom UI has been removed.

**Pull request closed without merging**
