### PR TITLE
Update PlayerUiController.kt

### PR DESCRIPTION
**Pull request by JosiYosi**
Adding an interface method showProgressBar and declare it

### CODE REVIEW

**Comment by PierfrancescoSoffritti** [comment]
Hi, what is the purpose of this method? and where is the implementation?

**Comment by PierfrancescoSoffritti** [comment]
I just saw the other PR. I don't think they should be separate.

**Comment by JosiYosi** [comment]
The purpose of adding that method was to disable a customized progress bar since the default one cannot be disabled. But in your other comment you have said that no need to worry about it anymore from version 11 bc the default player is webUi. If that is the case, no need to add the suggested method then.

**Comment by PierfrancescoSoffritti** [comment]
See #842

**Pull request closed without merging**
